services:
  - type: web
    name: paypay-vending-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -u start.py
    healthCheckPath: /health
    maxShutdownDelaySeconds: 30
